# ===================================================================
#                   General configuration
# ===================================================================

logging:
  level:
    dk.sunepoulsen.tes.springboot: INFO
